name: ci-golang-workflow
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test ./main/ -coverprofile="coverage.out"
      - run: go run ./main/math.go